packages:
  - "packages/*"
  - "apps/*"

linkWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build

allowBuilds:
  "@google/genai": false
  electron: true
  electron-winstaller: false
  esbuild: true
  protobufjs: false
  vue-demi: true

minimumReleaseAgeExclude:
  - electron@44.3.0
  - markstream-core@2.0.11
  - markstream-vue@2.0.11
  - stream-markdown-parser@1.2.16
