import { z } from "zod";
import {
  BootstrapExchangeResultSchema,
  BootstrapExchangeSchema,
  BootstrapSchema,
  LiveHealthSchema,
  ReadyHealthSchema,
} from "./bootstrap.js";
import {
  CommandOnlySchema,
  EmptySchema,
  PaginationQuerySchema,
  RevisionCommandSchema,
  cursorPageSchema,
  mutationResultSchema,
} from "./common.js";
import { EventsQuerySchema, GatewayEventSchema } from "./events.js";
import {
  AuthFlowIdSchema,
  ProviderIdSchema,
  RunIdSchema,
  SessionIdSchema,
  WorkspaceIdSchema,
} from "./ids.js";
import {
  AuthFlowSchema,
  CreateAuthFlowSchema,
  ModelSchema,
  ProviderAuthStatusSchema,
  RespondAuthFlowSchema,
  SetApiKeySchema,
} from "./model-auth.js";
import type { ProblemCode } from "./problem.js";
import {
  CancelRunSchema,
  CreateRunSchema,
  RunDetailSchema,
  RunSummarySchema,
  SteerRunSchema,
} from "./run.js";
import {
  CreateSessionSchema,
  SessionDetailSchema,
  SessionListQuerySchema,
  SessionSnapshotSchema,
  SessionSummarySchema,
  TranscriptPageSchema,
  UpdateSessionSchema,
} from "./session.js";
import {
  CreateWorkspacePreviewSchema,
  CreateWorkspaceSchema,
  UpdateWorkspaceSchema,
  WorkspaceDetailSchema,
  WorkspaceRegistrationPreviewSchema,
  WorkspaceSummarySchema,
} from "./workspace.js";

export type HttpMethod = "GET" | "POST" | "PATCH";
export type AuthorizationClass =
  "health" | "bootstrap" | "principal" | "workspace";
export interface EndpointDescriptor {
  readonly operationId: string;
  readonly method: HttpMethod;
  readonly path: string;
  readonly authorization: AuthorizationClass;
  readonly typedClientMethod: string;
  readonly pathSchema: z.ZodType;
  readonly querySchema: z.ZodType;
  readonly bodySchema: z.ZodType;
  readonly successStatus: 200 | 201 | 202;
  readonly successSchema: z.ZodType;
  readonly problemCodes: readonly ProblemCode[];
}
const requestProblems = [
  "request.validation_failed",
  "server.internal",
] as const;
const authProblems = [
  "auth.unauthenticated",
  "auth.csrf_invalid",
  "server.internal",
] as const;
const workspaceProblems = [
  "auth.forbidden",
  "workspace.not_found",
  "server.internal",
] as const;
const endpoint = (descriptor: EndpointDescriptor): EndpointDescriptor =>
  descriptor;
const path = <T extends z.ZodRawShape>(shape: T) => z.strictObject(shape);
const mutation = mutationResultSchema;

export const endpoints = [
  endpoint({
    operationId: "healthLive",
    method: "GET",
    path: "/api/v1/health/live",
    authorization: "health",
    typedClientMethod: "health.live",
    pathSchema: EmptySchema,
    querySchema: EmptySchema,
    bodySchema: EmptySchema,
    successStatus: 200,
    successSchema: LiveHealthSchema,
    problemCodes: ["server.internal"],
  }),
  endpoint({
    operationId: "healthReady",
    method: "GET",
    path: "/api/v1/health/ready",
    authorization: "health",
    typedClientMethod: "health.ready",
    pathSchema: EmptySchema,
    querySchema: EmptySchema,
    bodySchema: EmptySchema,
    successStatus: 200,
    successSchema: ReadyHealthSchema,
    problemCodes: ["server.unavailable"],
  }),
  endpoint({
    operationId: "gatewayAuthBootstrap",
    method: "POST",
    path: "/api/v1/gateway-auth/bootstrap",
    authorization: "bootstrap",
    typedClientMethod: "gatewayAuth.bootstrap",
    pathSchema: EmptySchema,
    querySchema: EmptySchema,
    bodySchema: BootstrapExchangeSchema,
    successStatus: 200,
    successSchema: BootstrapExchangeResultSchema,
    problemCodes: ["auth.bootstrap_invalid", ...requestProblems],
  }),
  endpoint({
    operationId: "getBootstrap",
    method: "GET",
    path: "/api/v1/bootstrap",
    authorization: "principal",
    typedClientMethod: "bootstrap.get",
    pathSchema: EmptySchema,
    querySchema: EmptySchema,
    bodySchema: EmptySchema,
    successStatus: 200,
    successSchema: BootstrapSchema,
    problemCodes: ["protocol.client_too_old", ...authProblems],
  }),
  endpoint({
    operationId: "openEvents",
    method: "GET",
    path: "/api/v1/events",
    authorization: "principal",
    typedClientMethod: "events.open",
    pathSchema: EmptySchema,
    querySchema: EventsQuerySchema,
    bodySchema: EmptySchema,
    successStatus: 200,
    successSchema: GatewayEventSchema,
    problemCodes: [
      "stream.cursor_invalid",
      "stream.replay_unavailable",
      ...authProblems,
    ],
  }),
  endpoint({
    operationId: "createWorkspaceRegistrationPreview",
    method: "POST",
    path: "/api/v1/workspace-registration-previews",
    authorization: "principal",
    typedClientMethod: "workspaces.preview",
    pathSchema: EmptySchema,
    querySchema: EmptySchema,
    bodySchema: CreateWorkspacePreviewSchema,
    successStatus: 201,
    successSchema: mutation(WorkspaceRegistrationPreviewSchema),
    problemCodes: ["workspace.path_invalid", ...authProblems],
  }),
  endpoint({
    operationId: "listWorkspaces",
    method: "GET",
    path: "/api/v1/workspaces",
    authorization: "principal",
    typedClientMethod: "workspaces.list",
    pathSchema: EmptySchema,
    querySchema: PaginationQuerySchema,
    bodySchema: EmptySchema,
    successStatus: 200,
    successSchema: cursorPageSchema(WorkspaceSummarySchema),
    problemCodes: authProblems,
  }),
  endpoint({
    operationId: "createWorkspace",
    method: "POST",
    path: "/api/v1/workspaces",
    authorization: "principal",
    typedClientMethod: "workspaces.create",
    pathSchema: EmptySchema,
    querySchema: EmptySchema,
    bodySchema: CreateWorkspaceSchema,
    successStatus: 201,
    successSchema: mutation(WorkspaceDetailSchema),
    problemCodes: [
      "workspace.registration_preview_invalid",
      "workspace.path_changed",
      ...authProblems,
    ],
  }),
  endpoint({
    operationId: "getWorkspace",
    method: "GET",
    path: "/api/v1/workspaces/:workspaceId",
    authorization: "workspace",
    typedClientMethod: "workspaces.get",
    pathSchema: path({ workspaceId: WorkspaceIdSchema }),
    querySchema: EmptySchema,
    bodySchema: EmptySchema,
    successStatus: 200,
    successSchema: WorkspaceDetailSchema,
    problemCodes: workspaceProblems,
  }),
  endpoint({
    operationId: "updateWorkspace",
    method: "PATCH",
    path: "/api/v1/workspaces/:workspaceId",
    authorization: "workspace",
    typedClientMethod: "workspaces.update",
    pathSchema: path({ workspaceId: WorkspaceIdSchema }),
    querySchema: EmptySchema,
    bodySchema: UpdateWorkspaceSchema,
    successStatus: 200,
    successSchema: mutation(WorkspaceDetailSchema),
    problemCodes: ["workspace.revision_conflict", ...workspaceProblems],
  }),
  endpoint({
    operationId: "unregisterWorkspace",
    method: "POST",
    path: "/api/v1/workspaces/:workspaceId/commands/unregister",
    authorization: "workspace",
    typedClientMethod: "workspaces.unregister",
    pathSchema: path({ workspaceId: WorkspaceIdSchema }),
    querySchema: EmptySchema,
    bodySchema: RevisionCommandSchema,
    successStatus: 200,
    successSchema: mutation(WorkspaceSummarySchema),
    problemCodes: [
      "workspace.revision_conflict",
      "workspace.in_use",
      ...workspaceProblems,
    ],
  }),
  endpoint({
    operationId: "listSessions",
    method: "GET",
    path: "/api/v1/workspaces/:workspaceId/sessions",
    authorization: "workspace",
    typedClientMethod: "sessions.list",
    pathSchema: path({ workspaceId: WorkspaceIdSchema }),
    querySchema: SessionListQuerySchema,
    bodySchema: EmptySchema,
    successStatus: 200,
    successSchema: cursorPageSchema(SessionSummarySchema),
    problemCodes: workspaceProblems,
  }),
  endpoint({
    operationId: "createSession",
    method: "POST",
    path: "/api/v1/workspaces/:workspaceId/sessions",
    authorization: "workspace",
    typedClientMethod: "sessions.create",
    pathSchema: path({ workspaceId: WorkspaceIdSchema }),
    querySchema: EmptySchema,
    bodySchema: CreateSessionSchema,
    successStatus: 201,
    successSchema: mutation(SessionDetailSchema),
    problemCodes: ["command.admission_closed", ...workspaceProblems],
  }),
  endpoint({
    operationId: "getSession",
    method: "GET",
    path: "/api/v1/sessions/:sessionId",
    authorization: "workspace",
    typedClientMethod: "sessions.get",
    pathSchema: path({ sessionId: SessionIdSchema }),
    querySchema: EmptySchema,
    bodySchema: EmptySchema,
    successStatus: 200,
    successSchema: SessionDetailSchema,
    problemCodes: ["session.not_found", ...workspaceProblems],
  }),
  endpoint({
    operationId: "updateSession",
    method: "PATCH",
    path: "/api/v1/sessions/:sessionId",
    authorization: "workspace",
    typedClientMethod: "sessions.update",
    pathSchema: path({ sessionId: SessionIdSchema }),
    querySchema: EmptySchema,
    bodySchema: UpdateSessionSchema,
    successStatus: 200,
    successSchema: mutation(SessionDetailSchema),
    problemCodes: [
      "session.not_found",
      "session.revision_conflict",
      "session.unavailable",
      ...workspaceProblems,
    ],
  }),
  endpoint({
    operationId: "deleteSession",
    method: "POST",
    path: "/api/v1/sessions/:sessionId/commands/delete",
    authorization: "workspace",
    typedClientMethod: "sessions.delete",
    pathSchema: path({ sessionId: SessionIdSchema }),
    querySchema: EmptySchema,
    bodySchema: RevisionCommandSchema,
    successStatus: 202,
    successSchema: mutation(SessionSummarySchema),
    problemCodes: [
      "session.not_found",
      "session.revision_conflict",
      "run.invalid_state",
      ...workspaceProblems,
    ],
  }),
  endpoint({
    operationId: "getSessionTranscript",
    method: "GET",
    path: "/api/v1/sessions/:sessionId/transcript",
    authorization: "workspace",
    typedClientMethod: "sessions.transcript",
    pathSchema: path({ sessionId: SessionIdSchema }),
    querySchema: PaginationQuerySchema,
    bodySchema: EmptySchema,
    successStatus: 200,
    successSchema: TranscriptPageSchema,
    problemCodes: ["session.not_found", ...workspaceProblems],
  }),
  endpoint({
    operationId: "getSessionSnapshot",
    method: "GET",
    path: "/api/v1/sessions/:sessionId/snapshot",
    authorization: "workspace",
    typedClientMethod: "sessions.snapshot",
    pathSchema: path({ sessionId: SessionIdSchema }),
    querySchema: EmptySchema,
    bodySchema: EmptySchema,
    successStatus: 200,
    successSchema: SessionSnapshotSchema,
    problemCodes: [
      "session.not_found",
      "session.unavailable",
      ...workspaceProblems,
    ],
  }),
  endpoint({
    operationId: "createRun",
    method: "POST",
    path: "/api/v1/sessions/:sessionId/runs",
    authorization: "workspace",
    typedClientMethod: "runs.create",
    pathSchema: path({ sessionId: SessionIdSchema }),
    querySchema: EmptySchema,
    bodySchema: CreateRunSchema,
    successStatus: 202,
    successSchema: mutation(RunSummarySchema),
    problemCodes: [
      "session.unavailable",
      "run.queue_full",
      "command.idempotency_conflict",
      "command.admission_closed",
      "model.not_found",
      "model.unavailable",
      "provider_auth.required",
      ...workspaceProblems,
    ],
  }),
  endpoint({
    operationId: "getRun",
    method: "GET",
    path: "/api/v1/runs/:runId",
    authorization: "workspace",
    typedClientMethod: "runs.get",
    pathSchema: path({ runId: RunIdSchema }),
    querySchema: EmptySchema,
    bodySchema: EmptySchema,
    successStatus: 200,
    successSchema: RunDetailSchema,
    problemCodes: ["run.not_found", ...workspaceProblems],
  }),
  endpoint({
    operationId: "steerRun",
    method: "POST",
    path: "/api/v1/runs/:runId/commands/steer",
    authorization: "workspace",
    typedClientMethod: "runs.steer",
    pathSchema: path({ runId: RunIdSchema }),
    querySchema: EmptySchema,
    bodySchema: SteerRunSchema,
    successStatus: 202,
    successSchema: mutation(RunSummarySchema),
    problemCodes: [
      "run.not_found",
      "run.invalid_state",
      "command.idempotency_conflict",
      ...workspaceProblems,
    ],
  }),
  endpoint({
    operationId: "cancelRun",
    method: "POST",
    path: "/api/v1/runs/:runId/commands/cancel",
    authorization: "workspace",
    typedClientMethod: "runs.cancel",
    pathSchema: path({ runId: RunIdSchema }),
    querySchema: EmptySchema,
    bodySchema: CancelRunSchema,
    successStatus: 202,
    successSchema: mutation(RunSummarySchema),
    problemCodes: [
      "run.not_found",
      "run.invalid_state",
      "command.idempotency_conflict",
      ...workspaceProblems,
    ],
  }),
  endpoint({
    operationId: "listModels",
    method: "GET",
    path: "/api/v1/models",
    authorization: "principal",
    typedClientMethod: "models.list",
    pathSchema: EmptySchema,
    querySchema: EmptySchema,
    bodySchema: EmptySchema,
    successStatus: 200,
    successSchema: z.array(ModelSchema),
    problemCodes: authProblems,
  }),
  endpoint({
    operationId: "listProviderAuth",
    method: "GET",
    path: "/api/v1/provider-auth",
    authorization: "principal",
    typedClientMethod: "providerAuth.list",
    pathSchema: EmptySchema,
    querySchema: EmptySchema,
    bodySchema: EmptySchema,
    successStatus: 200,
    successSchema: z.array(ProviderAuthStatusSchema),
    problemCodes: authProblems,
  }),
  endpoint({
    operationId: "setProviderApiKey",
    method: "POST",
    path: "/api/v1/provider-auth/:providerId/commands/set-api-key",
    authorization: "principal",
    typedClientMethod: "providerAuth.setApiKey",
    pathSchema: path({ providerId: ProviderIdSchema }),
    querySchema: EmptySchema,
    bodySchema: SetApiKeySchema,
    successStatus: 202,
    successSchema: mutation(ProviderAuthStatusSchema),
    problemCodes: ["provider_auth.required", ...authProblems],
  }),
  endpoint({
    operationId: "deleteProviderCredential",
    method: "POST",
    path: "/api/v1/provider-auth/:providerId/commands/delete-credential",
    authorization: "principal",
    typedClientMethod: "providerAuth.deleteCredential",
    pathSchema: path({ providerId: ProviderIdSchema }),
    querySchema: EmptySchema,
    bodySchema: CommandOnlySchema,
    successStatus: 202,
    successSchema: mutation(ProviderAuthStatusSchema),
    problemCodes: authProblems,
  }),
  endpoint({
    operationId: "createAuthFlow",
    method: "POST",
    path: "/api/v1/provider-auth/:providerId/auth-flows",
    authorization: "principal",
    typedClientMethod: "authFlows.create",
    pathSchema: path({ providerId: ProviderIdSchema }),
    querySchema: EmptySchema,
    bodySchema: CreateAuthFlowSchema,
    successStatus: 202,
    successSchema: mutation(AuthFlowSchema),
    problemCodes: ["provider_auth.required", ...authProblems],
  }),
  endpoint({
    operationId: "getAuthFlow",
    method: "GET",
    path: "/api/v1/auth-flows/:flowId",
    authorization: "principal",
    typedClientMethod: "authFlows.get",
    pathSchema: path({ flowId: AuthFlowIdSchema }),
    querySchema: EmptySchema,
    bodySchema: EmptySchema,
    successStatus: 200,
    successSchema: AuthFlowSchema,
    problemCodes: ["auth_flow.not_found", ...authProblems],
  }),
  endpoint({
    operationId: "respondAuthFlow",
    method: "POST",
    path: "/api/v1/auth-flows/:flowId/commands/respond",
    authorization: "principal",
    typedClientMethod: "authFlows.respond",
    pathSchema: path({ flowId: AuthFlowIdSchema }),
    querySchema: EmptySchema,
    bodySchema: RespondAuthFlowSchema,
    successStatus: 202,
    successSchema: mutation(AuthFlowSchema),
    problemCodes: [
      "auth_flow.not_found",
      "auth_flow.invalid_state",
      "auth_flow.expired",
      ...authProblems,
    ],
  }),
  endpoint({
    operationId: "cancelAuthFlow",
    method: "POST",
    path: "/api/v1/auth-flows/:flowId/commands/cancel",
    authorization: "principal",
    typedClientMethod: "authFlows.cancel",
    pathSchema: path({ flowId: AuthFlowIdSchema }),
    querySchema: EmptySchema,
    bodySchema: CommandOnlySchema,
    successStatus: 202,
    successSchema: mutation(AuthFlowSchema),
    problemCodes: [
      "auth_flow.not_found",
      "auth_flow.invalid_state",
      ...authProblems,
    ],
  }),
] as const satisfies readonly EndpointDescriptor[];

export type EndpointRegistry = typeof endpoints;
